# Generated by Django 4.2.16 on 2026-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonetizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monetization_enabled', models.BooleanField(default=False, help_text='If off, the site behaves as non-monetized (no paywalls / no upsell CTAs).')),
                ('monetization_starts_at', models.DateTimeField(blank=True, help_text='Optional. If set, monetization becomes active only after this date-time.', null=True)),
                ('gate_analytics', models.BooleanField(default=True)),
                ('gate_levels', models.BooleanField(default=True)),
                ('free_attempts_per_day', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monetization Settings',
                'verbose_name_plural': 'Monetization Settings',
            },
        ),
    ]
