# Generated by Django 4.2.16 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_monetizationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetizationsettings',
            name='monetize_after_days',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Delay paywalls for new users by N days after signup (0 = no delay).',
            ),
        ),
    ]

