# Generated by Django 4.2.16 on 2026-05-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_monetizationsettings_monetize_after_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(blank=True, help_text='Razorpay Key ID for checkout integration.', max_length=200)),
                ('key_secret', models.TextField(blank=True, help_text='Razorpay Key Secret. Keep this confidential and do not expose it in templates.')),
                ('webhook_secret', models.TextField(blank=True, help_text='Secret used to verify Razorpay webhook payloads.')),
                ('webhook_url', models.URLField(blank=True, help_text='Public Razorpay webhook URL. If blank, the default webhook endpoint will be used.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Razorpay Settings',
                'verbose_name_plural': 'Razorpay Settings',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount paid in INR for this subscription.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed')], default='pending', help_text='Current Razorpay payment status.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
