# Generated by Django 6.0.5 on 2026-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_razorpaywebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaysettings',
            name='razorpay_enabled',
            field=models.BooleanField(default=True, help_text='If disabled, users can subscribe directly without payment.'),
        ),
    ]
