# Generated by Django 4.2.16 on 2026-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], help_text='Question difficulty level (1 = easiest, 5 = hardest)', unique=True)),
                ('requires_membership', models.BooleanField(default=False, help_text='If checked, only paying members can access this level')),
                ('label', models.CharField(blank=True, help_text='Optional display label, e.g. "Beginner", "Advanced"', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Short description shown to users on the quiz start page', max_length=200)),
            ],
            options={
                'verbose_name': 'Level Configuration',
                'verbose_name_plural': 'Level Configurations',
                'ordering': ['level'],
            },
        ),
    ]
