# Generated by Django 4.2.16 on 2026-05-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_level_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Who uploaded/created this question (used for admin-only automation)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_questions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

