# Generated by Django 6.0.5 on 2026-06-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_add_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelconfig',
            name='max_questions',
            field=models.PositiveIntegerField(default=0, help_text='Max questions shown per quiz session at this level. 0 = no limit (show all).'),
        ),
    ]
