# Generated by Django 6.0.5 on 2026-06-06 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_levelconfig_max_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLevelTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.PositiveIntegerField()),
                ('new_level', models.PositiveIntegerField()),
                ('old_difficulty', models.CharField(max_length=10)),
                ('new_difficulty', models.CharField(max_length=10)),
                ('syllabus_name', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('topic_name', models.CharField(blank=True, max_length=200)),
                ('subtopic_name', models.CharField(blank=True, max_length=200)),
                ('correct_pct_at_transition', models.FloatField(help_text='Correct % in the last 100 attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_transitions', to='questions.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
