# Generated by Django 6.0.5 on 2026-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questionleveltransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formula',
            field=models.TextField(blank=True, help_text='Mathematical or scientific formula.'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url_extra',
            field=models.URLField(blank=True, help_text='Optional external diagram/image URL.'),
        ),
        migrations.AddField(
            model_name='question',
            name='latex_formula',
            field=models.TextField(blank=True, help_text='Optional LaTeX formatted formula.'),
        ),
        migrations.AddField(
            model_name='question',
            name='symbol_type',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology')], help_text='Category of symbols used.', max_length=50),
        ),
    ]
