# Generated by Django 4.2.16 on 2026-05-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('display_sidebar', 'Display Ad — Right Sidebar'), ('closing', 'Closing Ad — Between Questions'), ('overlapping', 'Overlapping Closing Ad — Interstitial')], max_length=30)),
                ('html_content', models.TextField(blank=True, help_text='Custom HTML/CSS for the promo ad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_ads/')),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_to_members', models.BooleanField(default=False, help_text='If False, shown to non-members only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
