# Generated by Django 4.2.16 on 2026-05-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Auto-filled from account', max_length=100)),
                ('body', models.TextField(help_text='Share your experience with the quiz platform')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('promoted', 'Promoted / Featured'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page / contact page hero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MCQ Platform', max_length=100)),
                ('home_title', models.CharField(default='MCQ Platform — Practice Topic-wise Questions', max_length=160)),
                ('home_description', models.TextField(default='Practice topic-wise MCQs with instant evaluation and performance tracking. Free and premium plans available.')),
                ('home_keywords', models.TextField(default='MCQ, multiple choice questions, exam preparation, quiz, practice test, aptitude, general knowledge')),
                ('og_image', models.ImageField(blank=True, help_text='Default Open Graph image (1200×630px)', null=True, upload_to='seo/')),
                ('twitter_handle', models.CharField(blank=True, help_text='@handle without @', max_length=50)),
                ('google_analytics', models.CharField(blank=True, help_text='GA4 Measurement ID e.g. G-XXXXXXXXXX', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
