# Generated by Django 4.2.16 on 2026-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('book', 'Book'), ('affiliate', 'Affiliate Link'), ('course', 'Online Course'), ('tool', 'Tool / Resource')], default='book', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('affiliate_url', models.URLField(blank=True, help_text='Buy / affiliate link (optional if you provide a downloadable file)')),
                ('download_file', models.FileField(blank=True, help_text='Optional downloadable file (PDF/ZIP/etc.)', null=True, upload_to='products/files/')),
                ('price_display', models.CharField(blank=True, help_text='e.g. ₹299 or Free', max_length=50)),
                ('badge', models.CharField(blank=True, help_text='e.g. Bestseller, Recommended', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
